variables:
  S3_BUCKET_NAME: "platform-static-dfms-front"
launch tests:
  image: adexlavid/npmpython:latest
  script:
  - npm install
  - npm run unit
build prod:
  image: adexlavid/npmpython:latest
  script:
  - npm install
  - npm run build
  - pip install awscli
  - aws s3 cp ./dist s3://$S3_BUCKET_NAME/ --recursive
  only:
    - dev